apiVersion: v1
kind: DeploymentConfig
metadata:
  name: gzd-batchkette
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deployment-config.name: gzd-batchkette
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deployment-config.name: gzd-batchkette
    spec:
      containers:
          envFrom:
            - configMapRef:
                name: gzd-batchkette-env
          image: >-
            registry.org/repository/some-image:0.1.22
          imagePullPolicy: Always
          name: default-container
          volumeMounts:
            - mountPath: /u01/oracle/datasources
              name: volume-gzd-batchkette-datasources
      volumes:
      - configMap:
          defaultMode: 420
          name: gzd-batchkette-datasources
        name: volume-gzd-batchkette-datasources
  triggers:
    - type: ConfigChange
